packagegroup-qti-core: Make packagegroup machine-specific to fix IPK error
Kirkstone upgrade causing below compilation error
  ERROR: packagegroup-qti-core-1.0-r0 do_package_write_ipk: An allarch packagegroup shouldn't depend on packages which are dynamically renamed
  for time-genoff-dev,time-genoff to libtime-genoff1,time-genoff-dbg to libtime-genoff-dbg.
  Fix:
  Added `PACKAGE_ARCH = "${MACHINE_ARCH}"`

Change-Id: I0ce55a795dd2463ceb56065642dfbbff7212df12
Signed-off-by: Deepak Dimri <ddimri@qti.qualcomm.com>