meta-qti-core: address time-genoff  compilation issue
Kirkstone GCC(11.3) will report below error for time-genoff
  ERROR: packagegroup-qti-core-1.0-r0 do_package_write_ipk:
  An allarch packagegroup shouldn't depend on packages which
  are dynamically renamed (time-genoff-dev to libtime-genoff-dev)

Change-Id: I4686cabccca1f23cae5ef403e0228a29065025ce
(cherry picked from commit f9ecee0d95befef2486cc9f7260b29889f9ff422)
(cherry picked from commit c31f9efa9bbf0da98178872c04599a25870c8780)